/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Alex Belalis Designs (https://sketchfab.com/alexbelalisdesigns)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mastered-ultra-instinct-goku-bba122ffa0d949cea97a67d21db87625
Title: Mastered Ultra Instinct - Goku
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations, useMotion } from '@react-three/drei'
import { useMotionValue, useSpring } from 'motion/react'
import { useFrame } from '@react-three/fiber'

export  default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/newmodels/mastered_ultra_instinct_-_goku.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if(animations.length > 0){
        actions[animations[0].name]?.play()
    }
  }, [actions, animations])
  const yPostion = useMotionValue(5)
  const ySpring =useSpring(yPostion, {damping:40 , stiffness: 100});
  
  useEffect(() => {
    ySpring.set(-1)
  }, [ySpring])
  useFrame(()=>{
    group.current.position.y = ySpring.get()
  })
  return (
    <group ref={group} {...props} dispose={null}
    rotation={[-Math.PI / 1.5, 0, 0]} scale={props.scale ||0.001 }
    position={props.position || [1.2, 2 , -2]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model"  >
          <group name="e1edc8b5e60b40c08c3d37fb6cd3ccfbfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Cube"
                   position={[376.541, 195.322, 324.586]}
                  rotation={[-Math.PI / 2, -0.2, 2.2]}
                  scale={127.151}>
                  <mesh
                    name="Cube__0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube__0.geometry}
                    material={materials.Cube__0}
                  />
                </group>
                <group
                  name="Sphere002"
                  position={[-15.255, 37.378, -22.856]}
                  rotation={[1.046, -0.034, 1.322]}
                  scale={[-0.728, -0.599, -1.197]}>
                  <mesh
                    name="Sphere002__0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere002__0.geometry}
                    material={materials.Cube__0}
                  />
                  <mesh
                    name="Sphere002__0_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere002__0_1.geometry}
                    material={materials.Cube__0}
                  />
                  <mesh
                    name="Sphere002__0_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere002__0_2.geometry}
                    material={materials.Cube__0}
                  />
                  <mesh
                    name="Sphere002__0_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere002__0_3.geometry}
                    material={materials.Cube__0}
                  />
                  <mesh
                    name="Sphere002__0_4"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere002__0_4.geometry}
                    material={materials.Cube__0}
                  />
                  <mesh
                    name="Sphere002__0_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere002__0_5.geometry}
                    material={materials.Cube__0}
                  />
                  <mesh
                    name="Sphere002__0_6"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere002__0_6.geometry}
                    material={materials.Cube__0}
                  />
                </group>
                <group name="Hair002" position={[4.665, -2.917, 23.597]} scale={100}>
                  <mesh
                    name="Hair002_Energy_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Hair002_Energy_0.geometry}
                    material={materials.Energy}
                  />
                  <mesh
                    name="Hair002_Energy_0_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Hair002_Energy_0_1.geometry}
                    material={materials.Energy}
                  />
                  <mesh
                    name="Hair002_Energy_0_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Hair002_Energy_0_2.geometry}
                    material={materials.Energy}
                  />
                  <mesh
                    name="Hair002_Energy_0_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.Hair002_Energy_0_3.geometry}
                    material={materials.Energy}
                  />
                </group>
                <group name="Hair001" position={[4.665, -2.917, 23.597]} scale={100}>
                  <mesh
                    name="Hair001_Energy_001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Hair001_Energy_001_0.geometry}
                    material={materials.Energy_001}
                  />
                  <mesh
                    name="Hair001_Energy_001_0_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Hair001_Energy_001_0_1.geometry}
                    material={materials.Energy_001}
                  />
                </group>
                <group
                  name="Head"
                  position={[-3.496, 702.009, -4.288]}
                  rotation={[-2.967, -1.484, Math.PI]}
                  scale={100}>
                  <mesh
                    name="Head_Material001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Head_Material001_0.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Clothes"
                  position={[0, 327.768, 36.245]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[243.001, 139.341, 252.795]}>
                  <mesh
                    name="Clothes_Material004_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Clothes_Material004_0.geometry}
                    material={materials['Material.004']}
                  />
                </group>
                <group
                  name="Ears"
                  position={[-92.75, 816.996, -6.761]}
                  rotation={[-1.574, 0.297, -0.59]}
                  scale={[7.286, 36.532, 47.917]}>
                  <mesh
                    name="Ears_Material003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Ears_Material003_0.geometry}
                    material={materials['Material.003']}
                  />
                </group>
                <group name="Hair" position={[4220.855, 19.419, 0]} scale={100}>
                  <mesh
                    name="Hair_GokuHair_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Hair_GokuHair_0.geometry}
                    material={materials.GokuHair}
                  />
                </group>
                <group name="Arms" position={[-105.526, -1710.55, 0]} scale={38.909}>
                  <mesh
                    name="Arms_Material002_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Arms_Material002_0.geometry}
                    material={materials['Material.002']}
                  />
                </group>
                <group
                  name="bracelet"
                  position={[-681.485, 361.045, -48.376]}
                  rotation={[-Math.PI / 2, 1.19, 0]}
                  scale={[63.783, 68.38, 63.783]}>
                  <mesh
                    name="bracelet_Material006_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bracelet_Material006_0.geometry}
                    material={materials['Material.006']}
                  />
                </group>
                <group
                  name="Plane009"
                  position={[214.309, 263.273, 17.866]}
                  rotation={[-1.341, -0.802, 1.814]}
                  scale={63.619}>
                  <mesh
                    name="Plane009_Material005_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane009_Material005_0.geometry}
                    material={materials['Material.005']}
                  />
                </group>
                <group
                  name="Shoes"
                  position={[-185.547, -1224.46, -224.359]}
                  rotation={[-2.93, 0.251, -0.081]}
                  scale={[-34.049, -30.958, -30.956]}>
                  <mesh
                    name="Shoes_tex4png_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Shoes_tex4png_0.geometry}
                    material={materials['tex4.png']}
                  />
                </group>
                <group
                  name="Sphere"
                  position={[376.384, 199.121, 325.005]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={81.439}>
                  <mesh
                    name="Sphere_Material009_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere_Material009_0.geometry}
                    material={materials['Material.009']}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/newmodels/mastered_ultra_instinct_-_goku.glb')
